name: poker-server
version: 0.1.0.0
github: "githubuser/poker-server"
license: Unlicense
author: "therewillbecode"
maintainer: "tom.chambrier@consensys.net"
copyright: "2018 Consensys"

extra-source-files:
  - README.md
  - ChangeLog.md

  # Metadata used when publishing your package
  # synopsis:            Short description of your package
  # category:            Web
  # To avoid duplicated efforts in documentation and dealing with the
  # complications of embedding Haddock markup inside cabal files, it is
  # common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/poker-server#readme>

dependencies:
  - base >= 4.12 && < 5
  - async
  - aeson
  - hedis
  - time
  - monad-logger
  - mtl
  - array
  - stm
  - ekg
  - containers
  - cryptohash
  - bytestring
  - servant-reason
  - reason-export
  - jose
  - persistent
  - persistent-postgresql
  - persistent-template
  - servant
  - time
  - servant-server
  - servant-foreign
  - servant-auth
  - servant-auth-server
  - servant-auth-client
  - servant-auth-swagger
  - servant-auth-docs
  - transformers
  - random
  - text
  - wai
  - wai-extra
  - wai-logger
  - wai-cors
  - websockets
  - pretty-simple
  - utf8-string
  - split
  - MonadRandom
  - jose
  - mtl
  - wuss
  - jwt
  - servant-docs
  - listsafe
  - warp
  - bytestring
  - lens
  - servant-options
  - async
  - vector

library:
  source-dirs: src
  exposed-modules:
    - API
    - Bots
    - Database
    - Schema
    - Env
    - Types
    - Poker.Poker
    - Poker.Game.Actions
    - Poker.ActionValidation
    - Poker.Types
    - Poker.Game.Blinds
    - Poker.Game.Game
    - Poker.Game.Hands
    - Poker.Game.Utils
    - Poker.Game.Privacy
    - Socket

executables:
  poker-server-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - poker-server

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - poker-server
      - hspec
      - hedgehog
      - hw-hspec-hedgehog
